config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'
  resources :posts do
    resources :comments
  end
  resources :projects

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: {minimum: 5}
	validates :body,  presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))

		redirect_to post_path(@post)
	end
	
	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	def index
		@posts = Post.all
	end

	def show
		#@post = Post.find(params[:id])
		#@post = find_post
	end

	def new 
		@post = Post.new 
	end

	def create
		@post = Post.new post_params
		#render plain: params[:post].inspect
		if @post.save 
			redirect_to @post, notice: "seifa go "
		else 
			render 'new', notice: "Ne go seifa"
		end
	end	

	def edit
		#post = post_params
		#@post = Post.find(params[:id])
	end 

	def update
		#@post = Post.find(params[:id])
		if @post.update post_params
			redirect_to @post , notice: "Successfuly Update"
		
		else 
			render 'edit'
		end
	end

	def destroy
		#@post = post_params
		@post.destroy
		redirect_to post_path
	end



	private

	def find_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :content)
	end	
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :find_project, only: [:show, :edit, :update, :destroy]
	def index
		@projects = Project.all.order("created_at desc")
	end
	def show
		
	end

	def new 
		@project = Project.new 
	end

	def create
		@project = Project.new project_params
		if @project.save 
			redirect_to @project, notice: "seifa go "
		else 
			render 'new', notice: "Ne go seifa"
		end
	end	

	def edit
		
	end 

	def update
		#@project = project.find(params[:id])
		if @project.update project_params
			redirect_to @project , notice: "Successfuly Update"
		
		else 
			render 'edit'
		end
	end

	def destroy
		#@project = project_params
		@project.destroy
		redirect_to project_path
	end



	private

	def find_project
		@project = Project.find(params[:id])
	end

	def project_params
		params.require(:project).permit(:title, :description, :link)
	end	

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@posts = Post.all.limit(3).order('created_at desc')
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comments.html.erb
<div class="comment">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
	</div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |c|%>
		
	<div class="input-group">
		<span class="input-group-addon" id="sizing-addon2">
			<%= c.label :name  %> 
		</span>
		
		<%= c.text_field :name ,:class => "form-control",  placeholder: "Name" %>
	</div>
			
	<div class="input-group">
		<span class="input-group-addon" id="sizing-addon2">
			<%= c.label :body  %>
		</span>	
		
		<%= c.text_area :body,:class => "form-control",  placeholder: "Body", rows:  "3" %>
	</div>
	<div class="submit-button">
		<%= c.submit nil, :class => "btn btn-info" %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
     <%= link_to  root_path  do %>
        <img alt="" src="/assets/blog.png">

      <% end %>
      <ul class="nav navbar-nav">
       
        <li><a href="#">Contacts</a></li>
       
        <li><%= link_to 'Projects', projects_path %></li>
        <li><%= link_to 'Blog', posts_path %></li>
       
        </ul>
       
      
    </div>
  </div>
</nav>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post  do |f| %>
	
	<% if @post.errors.any? %>
    	<div id="error_explanation">
      		<h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
			<ul>
      			<% @post.errors.full_messages.each do |message| %>
        			<li><%= message %></li>
      			<% end %>
      		</ul>
    	</div>
    <% end %>
	<div class="input-group">
		<span class="input-group-addon" id="sizing-addon2">
			<%= f.label :title  %> 
		</span>
		
		<%= f.text_field :title ,:class => "form-control",  placeholder: "Title" %>
	</div>
			
	<div class="input-group">
		<span class="input-group-addon" id="sizing-addon2">
			<%= f.label :content  %>
		</span>	
		
		<%= f.text_area :content,:class => "form-control",  placeholder: "Content", rows:  "8" %>
	</div>
	<div class="submit-button">
		<%= f.submit nil, :class => "btn btn-info" %>
		<%= link_to "Back", posts_path, :class => "btn btn-warning" %>
	</div>
<% end %>

app/views/posts/edit.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="panel panel-default">		
			<div class="panel-heading"><label>Edit Post</label></div>	
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>	

app/views/posts/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
	<div class="panel panel-default">		
		<div class="panel-heading">
		<label>All Posts</label>
		<%= link_to "New Post", new_post_path , :class => "btn btn-success"%>
		</div>	
		<table class="table">
			<tr>
			    <th>Title</th>
			    <th>Content</th>
			     <th>Created</th>
			</tr>
		  	<%  @posts.each do |p| %>
			  <tr>
			  	<td><%= p.title %> </td>
			    <td><%= p.content.first(25) %>...</td> 
			    <td><%= p.created_at.strftime('%A, %B, %d') %></td> 
			    <td><%= link_to 'Show', post_path(p), :class => "btn btn-info" %></td> 
			    <td><%= link_to 'Edit', edit_post_path(p), :class => "btn btn-warning"%></td> 
			    <td><%= link_to 'Delete', post_path(p),
			    										 method: :delete,
			    									     :class => "btn btn-danger"%></td> 
			  </tr>
		   	<% end %>
		</table>
		</div>
	</div>
</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
	<h3><label>New Post</label></h3>
	<%= render 'form' %> 

  </div>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  	<div class="show-form">
		<h2><label><%= @post.title %></label></h2>
		<label><%= @post.created_at.strftime('%A, %B, %d')%></label>
		<h5><label><%= @post.content %></label></h5>
			<div class="col-md-6 col-md-offset-3">
				<div id="comments">
					<h2><%= @post.comments.count %> Comments</h2>
					<%# render @post.comments %>

					<h3>Add a comment:</h3>
					<%= render "comments/form" %>
				</div>
				<%= link_to "Back", posts_path, :class => "btn btn-primary" %>
				<%= link_to 'Edit', edit_post_path(@post), :class => "btn btn-warning"%>
				<%= link_to 'Delete', post_path(@post),method: :delete,:class => "btn btn-danger"%></td> 
			</div>
			<br>
		
	</div>
	</div>
</div>

app/views/projects/_form.html.erb
<%= form_for @project  do |p| %>
	
	<% if @project.errors.any? %>
    	<div id="error_explanation">
      		<h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
			<ul>
      			<% @project.errors.full_messages.each do |message| %>
        			<li><%= message %></li>
      			<% end %>
      		</ul>
    	</div>
    <% end %>
	<div class="input-group">
		<span class="input-group-addon" id="sizing-addon2">
			<%=p.label :title  %> 
		</span>
		
		<%= p.text_field :title ,:class => "form-control",  placeholder: "Title" %>
	</div>
			
	<div class="input-group">
		<span class="input-group-addon" id="sizing-addon2">
			<%= p.label :description  %>
		</span>	
		
		<%= p.text_area :description,:class => "form-control",  placeholder: "Description", rows:  "5" %>
	</div>

	<div class="input-group">
		<span class="input-group-addon" id="sizing-addon2">
			<%=p.label :link  %> 
		</span>
		
		<%= p.text_field :link ,:class => "form-control",  placeholder: "Link" %>
	</div>
	<div class="submit-button">
		<%= p.submit nil, :class => "btn btn-info" %>
		<%= link_to "Back", projects_path, :class => "btn btn-warning" %>
	</div>
<% end %>

app/views/projects/edit.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="panel panel-default">		
			<div class="panel-heading"><label>Edit Project</label></div>	
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/projects/index.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  	<div class="project-index">
		
  	<%= @projects.each do |project|%>
		<h2><label><%= project.title %></label></h2>
		<label><%= project.created_at.strftime('%A, %B, %d')%></label>
		<h5><label><%= project.description %></label></h5>
		<label><%= project.link%></label><br>
		<%= link_to "Show", project, :class => "btn btn-primary" %>
		<%= link_to 'Edit', edit_project_path(project), :class => "btn btn-warning"%>
		<%= link_to 'Delete', project_path(project),method: :delete,:class => "btn btn-danger"%></td> 
		<hr class="speacial-hr">
	<% end %>
		
	</div>
	</div>
</div>

app/views/projects/new.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
	<h3><label>New Project</label></h3>
	<%= render 'form' %> 

  </div>
</div>

app/views/projects/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  	<div class="show-form">
		<h2><label><%= @project.title %></label></h2>
		<label><%= @project.created_at.strftime('%A, %B, %d')%></label>
		<h5><label><%= @project.description %></label></h5>
		<label><%= @project.link%></label><br>

		<%= link_to "Back", projects_path, :class => "btn btn-primary" %>
		<%= link_to 'Edit', edit_project_path(@project), :class => "btn btn-warning"%>
		<%= link_to 'Delete', project_path(@project),method: :delete,:class => "btn btn-danger"%></td> 
	</div>
	</div>
</div>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">


<div class="col-posts">
	<h3>Latest Blog Posts</h3>
	
	<table class="table">
			<tr>
			    <th>Title</th>
			    <th>Content</th>
			     <th>Created</th>
			</tr>
			<%  @posts.each do |p| %>
			 <tr>
			  	<td><%= link_to p.title, post_path(p) %> </td>
			    <td><%= p.content.first(25) %>...</td> 
			    <td><%= p.created_at.strftime('%A, %B, %d') %></td> 
			 </tr>
		   	<% end %>
		</table>
		
	<nav>
  <ul class="pager">
    <li class="previous "><a href="#"><span aria-hidden="true">&larr;</span> Older</a></li>
    <li class="next disabled"><a href="#">Newer <span aria-hidden="true">&rarr;</span></a></li>
  </ul>
</nav>
</div>

<div class="col-projects">
	<h3>Projects</h3>
	<hr class="speacial-hr">
	<h4>First Project</h4>
	Friday April 10
	<br>

	<h4>Secon Project</h4>
	Friday April 10
	<br>

	<h4>Third Project</h4>
	Friday April 10
	<br>
</div>
<div class="col-about">
	<h3>About</h3>
	<hr class="speacial-hr">
	<div class="col-about-img">
	<%= image_tag("photo.jpg") %>
	</div>
	<div class="col-about-text">
	<p>I am software developer &amp; designer living in Plovdiv, Bulgaria. </p>
	<p>By day I work as developer on rails applications by night i learn how to code on ruby :D</p>
	<p>You can find me ot Twitter,sharing some code on Github and sharing some jokes on Facebook</p>
	</div>
</div>
<footer>
<hr>

	<a href=""><label>Facebook</label></a>
	<a href=""><label>Twitter</label></a>
	<a href=""><label>GitHub</label></a>
</footer>
</div>
</div>